# CONSTANTS
WINDOW_WIDTH  = 640
WINDOW_HEIGHT = 480
FPS           = 30
BOARD_WIDTH   = 8
BOARD_HEIGHT  = 8
ROWS, COLS    = 8, 8
SQUARE_SIZE   = WINDOW_WIDTH // COLS

# RGB
WHITE         = (255, 255, 255)
BLACK         = (0, 0, 0)